services:
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entryPoints.streaming.address=:8000/tcp"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik


  app-stagging:
    image: ghcr.io/matheoelieg/cesicicd/app-rc:latest
    restart: always
    labels:
      - "traefik.http.routers.app-stagging.rule=Host(`cesi-stagging.mathdev.fr`)"
    networks:
      - traefik


networks:
  traefik:
    external: false
