name: GitHub Actions Demo
run-name: Build & test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci && npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: cypress/videos
          overwrite: true
      - run: npm run e2e:headless 

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: 22
          script: |
            cd cesicicd
            git pull
            npm run build 
            pm2 restart all
