name: GitHub Actions Demo
run-name: Build & test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache
      - run: npm ci
      - run: npm run e2e:headless 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: cypress/videos
          overwrite: true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache
      - run: npm ci
      - run: npm run build
